package com.gindevp.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AllocationRequestAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAllocationRequestAllPropertiesEquals(AllocationRequest expected, AllocationRequest actual) {
        assertAllocationRequestAutoGeneratedPropertiesEquals(expected, actual);
        assertAllocationRequestAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAllocationRequestAllUpdatablePropertiesEquals(AllocationRequest expected, AllocationRequest actual) {
        assertAllocationRequestUpdatableFieldsEquals(expected, actual);
        assertAllocationRequestUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAllocationRequestAutoGeneratedPropertiesEquals(AllocationRequest expected, AllocationRequest actual) {
        assertThat(expected)
            .as("Verify AllocationRequest auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAllocationRequestUpdatableFieldsEquals(AllocationRequest expected, AllocationRequest actual) {
        assertThat(expected)
            .as("Verify AllocationRequest relevant properties")
            .satisfies(e -> assertThat(e.getCode()).as("check code").isEqualTo(actual.getCode()))
            .satisfies(e -> assertThat(e.getRequestDate()).as("check requestDate").isEqualTo(actual.getRequestDate()))
            .satisfies(e -> assertThat(e.getReason()).as("check reason").isEqualTo(actual.getReason()))
            .satisfies(e -> assertThat(e.getStatus()).as("check status").isEqualTo(actual.getStatus()))
            .satisfies(e -> assertThat(e.getBeneficiaryNote()).as("check beneficiaryNote").isEqualTo(actual.getBeneficiaryNote()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAllocationRequestUpdatableRelationshipsEquals(AllocationRequest expected, AllocationRequest actual) {
        assertThat(expected)
            .as("Verify AllocationRequest relationships")
            .satisfies(e -> assertThat(e.getRequester()).as("check requester").isEqualTo(actual.getRequester()));
    }
}
