package com.gindevp.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AllocationRequestLineAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAllocationRequestLineAllPropertiesEquals(AllocationRequestLine expected, AllocationRequestLine actual) {
        assertAllocationRequestLineAutoGeneratedPropertiesEquals(expected, actual);
        assertAllocationRequestLineAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAllocationRequestLineAllUpdatablePropertiesEquals(
        AllocationRequestLine expected,
        AllocationRequestLine actual
    ) {
        assertAllocationRequestLineUpdatableFieldsEquals(expected, actual);
        assertAllocationRequestLineUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAllocationRequestLineAutoGeneratedPropertiesEquals(
        AllocationRequestLine expected,
        AllocationRequestLine actual
    ) {
        assertThat(expected)
            .as("Verify AllocationRequestLine auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAllocationRequestLineUpdatableFieldsEquals(AllocationRequestLine expected, AllocationRequestLine actual) {
        assertThat(expected)
            .as("Verify AllocationRequestLine relevant properties")
            .satisfies(e -> assertThat(e.getLineNo()).as("check lineNo").isEqualTo(actual.getLineNo()))
            .satisfies(e -> assertThat(e.getLineType()).as("check lineType").isEqualTo(actual.getLineType()))
            .satisfies(e -> assertThat(e.getQuantity()).as("check quantity").isEqualTo(actual.getQuantity()))
            .satisfies(e -> assertThat(e.getNote()).as("check note").isEqualTo(actual.getNote()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAllocationRequestLineUpdatableRelationshipsEquals(
        AllocationRequestLine expected,
        AllocationRequestLine actual
    ) {
        assertThat(expected)
            .as("Verify AllocationRequestLine relationships")
            .satisfies(e -> assertThat(e.getRequest()).as("check request").isEqualTo(actual.getRequest()))
            .satisfies(e -> assertThat(e.getAssetItem()).as("check assetItem").isEqualTo(actual.getAssetItem()))
            .satisfies(e -> assertThat(e.getAssetLine()).as("check assetLine").isEqualTo(actual.getAssetLine()));
    }
}
