package com.gindevp.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AssetLineAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAssetLineAllPropertiesEquals(AssetLine expected, AssetLine actual) {
        assertAssetLineAutoGeneratedPropertiesEquals(expected, actual);
        assertAssetLineAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAssetLineAllUpdatablePropertiesEquals(AssetLine expected, AssetLine actual) {
        assertAssetLineUpdatableFieldsEquals(expected, actual);
        assertAssetLineUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAssetLineAutoGeneratedPropertiesEquals(AssetLine expected, AssetLine actual) {
        assertThat(expected)
            .as("Verify AssetLine auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAssetLineUpdatableFieldsEquals(AssetLine expected, AssetLine actual) {
        assertThat(expected)
            .as("Verify AssetLine relevant properties")
            .satisfies(e -> assertThat(e.getCode()).as("check code").isEqualTo(actual.getCode()))
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()))
            .satisfies(e -> assertThat(e.getDescription()).as("check description").isEqualTo(actual.getDescription()))
            .satisfies(e -> assertThat(e.getActive()).as("check active").isEqualTo(actual.getActive()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAssetLineUpdatableRelationshipsEquals(AssetLine expected, AssetLine actual) {
        assertThat(expected)
            .as("Verify AssetLine relationships")
            .satisfies(e -> assertThat(e.getAssetGroup()).as("check assetGroup").isEqualTo(actual.getAssetGroup()));
    }
}
