package com.gindevp.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AssetItemAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAssetItemAllPropertiesEquals(AssetItem expected, AssetItem actual) {
        assertAssetItemAutoGeneratedPropertiesEquals(expected, actual);
        assertAssetItemAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAssetItemAllUpdatablePropertiesEquals(AssetItem expected, AssetItem actual) {
        assertAssetItemUpdatableFieldsEquals(expected, actual);
        assertAssetItemUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAssetItemAutoGeneratedPropertiesEquals(AssetItem expected, AssetItem actual) {
        assertThat(expected)
            .as("Verify AssetItem auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAssetItemUpdatableFieldsEquals(AssetItem expected, AssetItem actual) {
        assertThat(expected)
            .as("Verify AssetItem relevant properties")
            .satisfies(e -> assertThat(e.getCode()).as("check code").isEqualTo(actual.getCode()))
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()))
            .satisfies(e -> assertThat(e.getManagementType()).as("check managementType").isEqualTo(actual.getManagementType()))
            .satisfies(e -> assertThat(e.getUnit()).as("check unit").isEqualTo(actual.getUnit()))
            .satisfies(e ->
                assertThat(e.getDepreciationEnabled()).as("check depreciationEnabled").isEqualTo(actual.getDepreciationEnabled())
            )
            .satisfies(e ->
                assertThat(e.getSerialTrackingRequired()).as("check serialTrackingRequired").isEqualTo(actual.getSerialTrackingRequired())
            )
            .satisfies(e -> assertThat(e.getNote()).as("check note").isEqualTo(actual.getNote()))
            .satisfies(e -> assertThat(e.getActive()).as("check active").isEqualTo(actual.getActive()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAssetItemUpdatableRelationshipsEquals(AssetItem expected, AssetItem actual) {
        assertThat(expected)
            .as("Verify AssetItem relationships")
            .satisfies(e -> assertThat(e.getAssetLine()).as("check assetLine").isEqualTo(actual.getAssetLine()));
    }
}
