package com.gindevp.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AssetGroupAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAssetGroupAllPropertiesEquals(AssetGroup expected, AssetGroup actual) {
        assertAssetGroupAutoGeneratedPropertiesEquals(expected, actual);
        assertAssetGroupAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAssetGroupAllUpdatablePropertiesEquals(AssetGroup expected, AssetGroup actual) {
        assertAssetGroupUpdatableFieldsEquals(expected, actual);
        assertAssetGroupUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAssetGroupAutoGeneratedPropertiesEquals(AssetGroup expected, AssetGroup actual) {
        assertThat(expected)
            .as("Verify AssetGroup auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAssetGroupUpdatableFieldsEquals(AssetGroup expected, AssetGroup actual) {
        assertThat(expected)
            .as("Verify AssetGroup relevant properties")
            .satisfies(e -> assertThat(e.getCode()).as("check code").isEqualTo(actual.getCode()))
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()))
            .satisfies(e -> assertThat(e.getDescription()).as("check description").isEqualTo(actual.getDescription()))
            .satisfies(e -> assertThat(e.getActive()).as("check active").isEqualTo(actual.getActive()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAssetGroupUpdatableRelationshipsEquals(AssetGroup expected, AssetGroup actual) {
        assertThat(expected)
            .as("Verify AssetGroup relationships")
            .satisfies(e -> assertThat(e.getAssetType()).as("check assetType").isEqualTo(actual.getAssetType()));
    }
}
