package com.gindevp.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AssetTypeAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAssetTypeAllPropertiesEquals(AssetType expected, AssetType actual) {
        assertAssetTypeAutoGeneratedPropertiesEquals(expected, actual);
        assertAssetTypeAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAssetTypeAllUpdatablePropertiesEquals(AssetType expected, AssetType actual) {
        assertAssetTypeUpdatableFieldsEquals(expected, actual);
        assertAssetTypeUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAssetTypeAutoGeneratedPropertiesEquals(AssetType expected, AssetType actual) {
        assertThat(expected)
            .as("Verify AssetType auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAssetTypeUpdatableFieldsEquals(AssetType expected, AssetType actual) {
        assertThat(expected)
            .as("Verify AssetType relevant properties")
            .satisfies(e -> assertThat(e.getCode()).as("check code").isEqualTo(actual.getCode()))
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()))
            .satisfies(e -> assertThat(e.getDescription()).as("check description").isEqualTo(actual.getDescription()))
            .satisfies(e -> assertThat(e.getActive()).as("check active").isEqualTo(actual.getActive()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAssetTypeUpdatableRelationshipsEquals(AssetType expected, AssetType actual) {
        // empty method
    }
}
