package com.gindevp.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ConsumableAssignmentAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConsumableAssignmentAllPropertiesEquals(ConsumableAssignment expected, ConsumableAssignment actual) {
        assertConsumableAssignmentAutoGeneratedPropertiesEquals(expected, actual);
        assertConsumableAssignmentAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConsumableAssignmentAllUpdatablePropertiesEquals(ConsumableAssignment expected, ConsumableAssignment actual) {
        assertConsumableAssignmentUpdatableFieldsEquals(expected, actual);
        assertConsumableAssignmentUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConsumableAssignmentAutoGeneratedPropertiesEquals(ConsumableAssignment expected, ConsumableAssignment actual) {
        assertThat(expected)
            .as("Verify ConsumableAssignment auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConsumableAssignmentUpdatableFieldsEquals(ConsumableAssignment expected, ConsumableAssignment actual) {
        assertThat(expected)
            .as("Verify ConsumableAssignment relevant properties")
            .satisfies(e -> assertThat(e.getQuantity()).as("check quantity").isEqualTo(actual.getQuantity()))
            .satisfies(e -> assertThat(e.getAssignedDate()).as("check assignedDate").isEqualTo(actual.getAssignedDate()))
            .satisfies(e -> assertThat(e.getReturnedQuantity()).as("check returnedQuantity").isEqualTo(actual.getReturnedQuantity()))
            .satisfies(e -> assertThat(e.getNote()).as("check note").isEqualTo(actual.getNote()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConsumableAssignmentUpdatableRelationshipsEquals(ConsumableAssignment expected, ConsumableAssignment actual) {
        assertThat(expected)
            .as("Verify ConsumableAssignment relationships")
            .satisfies(e -> assertThat(e.getAssetItem()).as("check assetItem").isEqualTo(actual.getAssetItem()))
            .satisfies(e -> assertThat(e.getEmployee()).as("check employee").isEqualTo(actual.getEmployee()))
            .satisfies(e -> assertThat(e.getDepartment()).as("check department").isEqualTo(actual.getDepartment()))
            .satisfies(e -> assertThat(e.getLocation()).as("check location").isEqualTo(actual.getLocation()));
    }
}
