package com.gindevp.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ConsumableStockAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConsumableStockAllPropertiesEquals(ConsumableStock expected, ConsumableStock actual) {
        assertConsumableStockAutoGeneratedPropertiesEquals(expected, actual);
        assertConsumableStockAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConsumableStockAllUpdatablePropertiesEquals(ConsumableStock expected, ConsumableStock actual) {
        assertConsumableStockUpdatableFieldsEquals(expected, actual);
        assertConsumableStockUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConsumableStockAutoGeneratedPropertiesEquals(ConsumableStock expected, ConsumableStock actual) {
        assertThat(expected)
            .as("Verify ConsumableStock auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConsumableStockUpdatableFieldsEquals(ConsumableStock expected, ConsumableStock actual) {
        assertThat(expected)
            .as("Verify ConsumableStock relevant properties")
            .satisfies(e -> assertThat(e.getQuantityOnHand()).as("check quantityOnHand").isEqualTo(actual.getQuantityOnHand()))
            .satisfies(e -> assertThat(e.getQuantityIssued()).as("check quantityIssued").isEqualTo(actual.getQuantityIssued()))
            .satisfies(e -> assertThat(e.getNote()).as("check note").isEqualTo(actual.getNote()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConsumableStockUpdatableRelationshipsEquals(ConsumableStock expected, ConsumableStock actual) {
        assertThat(expected)
            .as("Verify ConsumableStock relationships")
            .satisfies(e -> assertThat(e.getAssetItem()).as("check assetItem").isEqualTo(actual.getAssetItem()));
    }
}
