package com.gindevp.app.domain;

import static com.gindevp.app.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class EquipmentAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEquipmentAllPropertiesEquals(Equipment expected, Equipment actual) {
        assertEquipmentAutoGeneratedPropertiesEquals(expected, actual);
        assertEquipmentAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEquipmentAllUpdatablePropertiesEquals(Equipment expected, Equipment actual) {
        assertEquipmentUpdatableFieldsEquals(expected, actual);
        assertEquipmentUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEquipmentAutoGeneratedPropertiesEquals(Equipment expected, Equipment actual) {
        assertThat(expected)
            .as("Verify Equipment auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEquipmentUpdatableFieldsEquals(Equipment expected, Equipment actual) {
        assertThat(expected)
            .as("Verify Equipment relevant properties")
            .satisfies(e -> assertThat(e.getEquipmentCode()).as("check equipmentCode").isEqualTo(actual.getEquipmentCode()))
            .satisfies(e -> assertThat(e.getSerial()).as("check serial").isEqualTo(actual.getSerial()))
            .satisfies(e -> assertThat(e.getModelName()).as("check modelName").isEqualTo(actual.getModelName()))
            .satisfies(e -> assertThat(e.getBrandName()).as("check brandName").isEqualTo(actual.getBrandName()))
            .satisfies(e -> assertThat(e.getConditionNote()).as("check conditionNote").isEqualTo(actual.getConditionNote()))
            .satisfies(e -> assertThat(e.getStatus()).as("check status").isEqualTo(actual.getStatus()))
            .satisfies(e ->
                assertThat(e.getPurchasePrice())
                    .as("check purchasePrice")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(actual.getPurchasePrice())
            )
            .satisfies(e -> assertThat(e.getCapitalizationDate()).as("check capitalizationDate").isEqualTo(actual.getCapitalizationDate()))
            .satisfies(e -> assertThat(e.getDepreciationMonths()).as("check depreciationMonths").isEqualTo(actual.getDepreciationMonths()))
            .satisfies(e ->
                assertThat(e.getSalvageValue())
                    .as("check salvageValue")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(actual.getSalvageValue())
            )
            .satisfies(e ->
                assertThat(e.getBookValueSnapshot())
                    .as("check bookValueSnapshot")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(actual.getBookValueSnapshot())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEquipmentUpdatableRelationshipsEquals(Equipment expected, Equipment actual) {
        assertThat(expected)
            .as("Verify Equipment relationships")
            .satisfies(e -> assertThat(e.getAssetItem()).as("check assetItem").isEqualTo(actual.getAssetItem()))
            .satisfies(e -> assertThat(e.getSupplier()).as("check supplier").isEqualTo(actual.getSupplier()));
    }
}
