package com.gindevp.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class EquipmentAssignmentAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEquipmentAssignmentAllPropertiesEquals(EquipmentAssignment expected, EquipmentAssignment actual) {
        assertEquipmentAssignmentAutoGeneratedPropertiesEquals(expected, actual);
        assertEquipmentAssignmentAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEquipmentAssignmentAllUpdatablePropertiesEquals(EquipmentAssignment expected, EquipmentAssignment actual) {
        assertEquipmentAssignmentUpdatableFieldsEquals(expected, actual);
        assertEquipmentAssignmentUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEquipmentAssignmentAutoGeneratedPropertiesEquals(EquipmentAssignment expected, EquipmentAssignment actual) {
        assertThat(expected)
            .as("Verify EquipmentAssignment auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEquipmentAssignmentUpdatableFieldsEquals(EquipmentAssignment expected, EquipmentAssignment actual) {
        assertThat(expected)
            .as("Verify EquipmentAssignment relevant properties")
            .satisfies(e -> assertThat(e.getAssignedDate()).as("check assignedDate").isEqualTo(actual.getAssignedDate()))
            .satisfies(e -> assertThat(e.getReturnedDate()).as("check returnedDate").isEqualTo(actual.getReturnedDate()))
            .satisfies(e -> assertThat(e.getNote()).as("check note").isEqualTo(actual.getNote()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEquipmentAssignmentUpdatableRelationshipsEquals(EquipmentAssignment expected, EquipmentAssignment actual) {
        assertThat(expected)
            .as("Verify EquipmentAssignment relationships")
            .satisfies(e -> assertThat(e.getEquipment()).as("check equipment").isEqualTo(actual.getEquipment()))
            .satisfies(e -> assertThat(e.getEmployee()).as("check employee").isEqualTo(actual.getEmployee()))
            .satisfies(e -> assertThat(e.getDepartment()).as("check department").isEqualTo(actual.getDepartment()))
            .satisfies(e -> assertThat(e.getLocation()).as("check location").isEqualTo(actual.getLocation()));
    }
}
