package com.gindevp.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ReturnRequestLineAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReturnRequestLineAllPropertiesEquals(ReturnRequestLine expected, ReturnRequestLine actual) {
        assertReturnRequestLineAutoGeneratedPropertiesEquals(expected, actual);
        assertReturnRequestLineAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReturnRequestLineAllUpdatablePropertiesEquals(ReturnRequestLine expected, ReturnRequestLine actual) {
        assertReturnRequestLineUpdatableFieldsEquals(expected, actual);
        assertReturnRequestLineUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReturnRequestLineAutoGeneratedPropertiesEquals(ReturnRequestLine expected, ReturnRequestLine actual) {
        assertThat(expected)
            .as("Verify ReturnRequestLine auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReturnRequestLineUpdatableFieldsEquals(ReturnRequestLine expected, ReturnRequestLine actual) {
        assertThat(expected)
            .as("Verify ReturnRequestLine relevant properties")
            .satisfies(e -> assertThat(e.getLineNo()).as("check lineNo").isEqualTo(actual.getLineNo()))
            .satisfies(e -> assertThat(e.getLineType()).as("check lineType").isEqualTo(actual.getLineType()))
            .satisfies(e -> assertThat(e.getQuantity()).as("check quantity").isEqualTo(actual.getQuantity()))
            .satisfies(e -> assertThat(e.getSelected()).as("check selected").isEqualTo(actual.getSelected()))
            .satisfies(e -> assertThat(e.getNote()).as("check note").isEqualTo(actual.getNote()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReturnRequestLineUpdatableRelationshipsEquals(ReturnRequestLine expected, ReturnRequestLine actual) {
        assertThat(expected)
            .as("Verify ReturnRequestLine relationships")
            .satisfies(e -> assertThat(e.getRequest()).as("check request").isEqualTo(actual.getRequest()))
            .satisfies(e -> assertThat(e.getAssetItem()).as("check assetItem").isEqualTo(actual.getAssetItem()))
            .satisfies(e -> assertThat(e.getEquipment()).as("check equipment").isEqualTo(actual.getEquipment()));
    }
}
