package com.gindevp.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ReturnRequestAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReturnRequestAllPropertiesEquals(ReturnRequest expected, ReturnRequest actual) {
        assertReturnRequestAutoGeneratedPropertiesEquals(expected, actual);
        assertReturnRequestAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReturnRequestAllUpdatablePropertiesEquals(ReturnRequest expected, ReturnRequest actual) {
        assertReturnRequestUpdatableFieldsEquals(expected, actual);
        assertReturnRequestUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReturnRequestAutoGeneratedPropertiesEquals(ReturnRequest expected, ReturnRequest actual) {
        assertThat(expected)
            .as("Verify ReturnRequest auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReturnRequestUpdatableFieldsEquals(ReturnRequest expected, ReturnRequest actual) {
        assertThat(expected)
            .as("Verify ReturnRequest relevant properties")
            .satisfies(e -> assertThat(e.getCode()).as("check code").isEqualTo(actual.getCode()))
            .satisfies(e -> assertThat(e.getRequestDate()).as("check requestDate").isEqualTo(actual.getRequestDate()))
            .satisfies(e -> assertThat(e.getNote()).as("check note").isEqualTo(actual.getNote()))
            .satisfies(e -> assertThat(e.getStatus()).as("check status").isEqualTo(actual.getStatus()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReturnRequestUpdatableRelationshipsEquals(ReturnRequest expected, ReturnRequest actual) {
        assertThat(expected)
            .as("Verify ReturnRequest relationships")
            .satisfies(e -> assertThat(e.getRequester()).as("check requester").isEqualTo(actual.getRequester()));
    }
}
