package com.gindevp.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class StockIssueLineAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStockIssueLineAllPropertiesEquals(StockIssueLine expected, StockIssueLine actual) {
        assertStockIssueLineAutoGeneratedPropertiesEquals(expected, actual);
        assertStockIssueLineAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStockIssueLineAllUpdatablePropertiesEquals(StockIssueLine expected, StockIssueLine actual) {
        assertStockIssueLineUpdatableFieldsEquals(expected, actual);
        assertStockIssueLineUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStockIssueLineAutoGeneratedPropertiesEquals(StockIssueLine expected, StockIssueLine actual) {
        assertThat(expected)
            .as("Verify StockIssueLine auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStockIssueLineUpdatableFieldsEquals(StockIssueLine expected, StockIssueLine actual) {
        assertThat(expected)
            .as("Verify StockIssueLine relevant properties")
            .satisfies(e -> assertThat(e.getLineNo()).as("check lineNo").isEqualTo(actual.getLineNo()))
            .satisfies(e -> assertThat(e.getQuantity()).as("check quantity").isEqualTo(actual.getQuantity()))
            .satisfies(e -> assertThat(e.getNote()).as("check note").isEqualTo(actual.getNote()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStockIssueLineUpdatableRelationshipsEquals(StockIssueLine expected, StockIssueLine actual) {
        assertThat(expected)
            .as("Verify StockIssueLine relationships")
            .satisfies(e -> assertThat(e.getIssue()).as("check issue").isEqualTo(actual.getIssue()))
            .satisfies(e -> assertThat(e.getAssetItem()).as("check assetItem").isEqualTo(actual.getAssetItem()))
            .satisfies(e -> assertThat(e.getEquipment()).as("check equipment").isEqualTo(actual.getEquipment()));
    }
}
