package com.gindevp.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class StockReceiptAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStockReceiptAllPropertiesEquals(StockReceipt expected, StockReceipt actual) {
        assertStockReceiptAutoGeneratedPropertiesEquals(expected, actual);
        assertStockReceiptAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStockReceiptAllUpdatablePropertiesEquals(StockReceipt expected, StockReceipt actual) {
        assertStockReceiptUpdatableFieldsEquals(expected, actual);
        assertStockReceiptUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStockReceiptAutoGeneratedPropertiesEquals(StockReceipt expected, StockReceipt actual) {
        assertThat(expected)
            .as("Verify StockReceipt auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStockReceiptUpdatableFieldsEquals(StockReceipt expected, StockReceipt actual) {
        assertThat(expected)
            .as("Verify StockReceipt relevant properties")
            .satisfies(e -> assertThat(e.getCode()).as("check code").isEqualTo(actual.getCode()))
            .satisfies(e -> assertThat(e.getReceiptDate()).as("check receiptDate").isEqualTo(actual.getReceiptDate()))
            .satisfies(e -> assertThat(e.getSource()).as("check source").isEqualTo(actual.getSource()))
            .satisfies(e -> assertThat(e.getStatus()).as("check status").isEqualTo(actual.getStatus()))
            .satisfies(e -> assertThat(e.getNote()).as("check note").isEqualTo(actual.getNote()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStockReceiptUpdatableRelationshipsEquals(StockReceipt expected, StockReceipt actual) {
        // empty method
    }
}
