package com.gindevp.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class StockIssueAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStockIssueAllPropertiesEquals(StockIssue expected, StockIssue actual) {
        assertStockIssueAutoGeneratedPropertiesEquals(expected, actual);
        assertStockIssueAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStockIssueAllUpdatablePropertiesEquals(StockIssue expected, StockIssue actual) {
        assertStockIssueUpdatableFieldsEquals(expected, actual);
        assertStockIssueUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStockIssueAutoGeneratedPropertiesEquals(StockIssue expected, StockIssue actual) {
        assertThat(expected)
            .as("Verify StockIssue auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStockIssueUpdatableFieldsEquals(StockIssue expected, StockIssue actual) {
        assertThat(expected)
            .as("Verify StockIssue relevant properties")
            .satisfies(e -> assertThat(e.getCode()).as("check code").isEqualTo(actual.getCode()))
            .satisfies(e -> assertThat(e.getIssueDate()).as("check issueDate").isEqualTo(actual.getIssueDate()))
            .satisfies(e -> assertThat(e.getStatus()).as("check status").isEqualTo(actual.getStatus()))
            .satisfies(e -> assertThat(e.getAssigneeType()).as("check assigneeType").isEqualTo(actual.getAssigneeType()))
            .satisfies(e -> assertThat(e.getNote()).as("check note").isEqualTo(actual.getNote()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStockIssueUpdatableRelationshipsEquals(StockIssue expected, StockIssue actual) {
        assertThat(expected)
            .as("Verify StockIssue relationships")
            .satisfies(e -> assertThat(e.getEmployee()).as("check employee").isEqualTo(actual.getEmployee()))
            .satisfies(e -> assertThat(e.getDepartment()).as("check department").isEqualTo(actual.getDepartment()))
            .satisfies(e -> assertThat(e.getLocation()).as("check location").isEqualTo(actual.getLocation()));
    }
}
