package com.gindevp.app.domain;

import static com.gindevp.app.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class StockReceiptLineAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStockReceiptLineAllPropertiesEquals(StockReceiptLine expected, StockReceiptLine actual) {
        assertStockReceiptLineAutoGeneratedPropertiesEquals(expected, actual);
        assertStockReceiptLineAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStockReceiptLineAllUpdatablePropertiesEquals(StockReceiptLine expected, StockReceiptLine actual) {
        assertStockReceiptLineUpdatableFieldsEquals(expected, actual);
        assertStockReceiptLineUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStockReceiptLineAutoGeneratedPropertiesEquals(StockReceiptLine expected, StockReceiptLine actual) {
        assertThat(expected)
            .as("Verify StockReceiptLine auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStockReceiptLineUpdatableFieldsEquals(StockReceiptLine expected, StockReceiptLine actual) {
        assertThat(expected)
            .as("Verify StockReceiptLine relevant properties")
            .satisfies(e -> assertThat(e.getLineNo()).as("check lineNo").isEqualTo(actual.getLineNo()))
            .satisfies(e -> assertThat(e.getQuantity()).as("check quantity").isEqualTo(actual.getQuantity()))
            .satisfies(e ->
                assertThat(e.getUnitPrice()).as("check unitPrice").usingComparator(bigDecimalCompareTo).isEqualTo(actual.getUnitPrice())
            )
            .satisfies(e -> assertThat(e.getNote()).as("check note").isEqualTo(actual.getNote()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStockReceiptLineUpdatableRelationshipsEquals(StockReceiptLine expected, StockReceiptLine actual) {
        assertThat(expected)
            .as("Verify StockReceiptLine relationships")
            .satisfies(e -> assertThat(e.getReceipt()).as("check receipt").isEqualTo(actual.getReceipt()))
            .satisfies(e -> assertThat(e.getAssetItem()).as("check assetItem").isEqualTo(actual.getAssetItem()));
    }
}
